### PR TITLE
chore: added in CODEOWNERS

### PR DESCRIPTION
**Pull request by MikAoJk**

### CODE REVIEW

**Comment by MikAoJk** [comment]
@haakonhelmenrusas

**Comment by MikAoJk** [comment]
Motivation: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by haakonhelmenrusas** [comment]
Thank you for the tip and contribution!

**Comment by MikAoJk** [comment]
> Thank you for the tip and contribution!

np

**Pull request merged**
